### ISSUE TITLE
"Pincode TouchID" in Touch ID dialog

### ISSUE THREAD

**Issue by sergpol** [SugarAndCandy/SCPinViewController#4]
Can i change this "Pincode TouchID" string in Touch ID dialog?

**Comment by makleso6** [comment]
@sergpol screen plz

**Comment by makleso6** [comment]
@sergpol fix

**Comment by sergpol** [comment]
Version 1.0.2 still unavailable for PODs, i can't install it via 'pod update' or 'pod install'

**Comment by makleso6** [comment]
@sergpol fixed

**Comment by sergpol** [comment]
Great, thanks!!!
