### ISSUE TITLE
SCPinAppearance set custom text when wrong attempts

### ISSUE THREAD

**Issue by Rupasekhar** [SugarAndCandy/SCPinViewController#6]
Hi

My issue is, unable to set custom text when user given wrong pin number.

```
-(void)pinViewControllerDidSetWrongPin:(SCPinViewController *)pinViewController
{
    wrongAttemptCount++;
    if (wrongAttemptCount>5)
    {
        wrongAttemptCount = 0;
        SCPinAppearance *appearance = [SCPinAppearance defaultAppearance];
        appearance.numberButtonstrokeEnabled = NO;
        appearance.titleText = @"5 consecutive wrong attempts, Screen will be unfreeze after 30 sec.";
        [SCPinViewController setNewAppearance:appearance];
        [[UIApplication sharedApplication] beginIgnoringInteractionEvents];
        [NSTimer scheduledTimerWithTimeInterval:30.0 target:self selector:@selector(unfreezeTheUIMethod) userInfo:nil repeats:NO];
        NSLog(@"Wrong attempt");
    }
}
```

and this is my code, for setting custom text. Please help me out ASAP.

**Comment by makleso6** [comment]
Library does not support, please make a fork and add custom changes
for example add method
```
-(void)setNewAppearance:(SCPinAppearance *) appearance {
     _appearance = appearance;
    [self configureView];
}
```

**Comment by Rupasekhar** [comment]
@makleso6 , When I'm adding  [self configureView]; this line giving the following error. Please check the attached screenshot.
Help me out please....!!!!
![screen shot 2018-09-26 at 2 36 58 pm](https://user-images.githubusercontent.com/2901360/46069714-becc0980-c199-11e8-926b-0110794f838b.png)

**Comment by Rupasekhar** [comment]
> Library does not support, please make a fork and add custom changes
> for example add method
> 
> ```
> -(void)setNewAppearance:(SCPinAppearance *) appearance {
>      _appearance = appearance;
>     [self configureView];
> }
> ```

![screen shot 2018-09-26 at 2 36 58 pm](https://user-images.githubusercontent.com/2901360/46073557-e1165500-c1a2-11e8-975b-5ba7c587724d.png)

**Comment by makleso6** [comment]
`-(void)setNewAppearance:(SCPinAppearance *) appearance` 
Not the same
`+(void)setNewAppearance:(SCPinAppearance *) appearance` 


create NEW method
